# Generated by Django 2.2.12 on 2020-04-20 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='from_user',
        ),
        migrations.AddField(
            model_name='chat',
            name='log',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_by_room', to='chat.Room'),
            preserve_default=False,
        ),
    ]
