# Generated by Django 2.2.12 on 2020-04-20 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200420_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
